Running on Colab, will download and install neccesary packages.
upload the "newBenchmarks_dataset.xlsx" in the main folder

In [ ]:
!pip install tensorboardX
!pip install pysr

Collecting tensorboardX
  Downloading tensorboardx-2.6.5-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from tensorboardX) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorboardX) (26.2)
Requirement already satisfied: protobuf>=3.20 in /usr/local/lib/python3.12/dist-packages (from tensorboardX) (5.29.6)
Downloading tensorboardx-2.6.5-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 1.8 MB/s eta 0:00:00
Installing collected packages: tensorboardX
Successfully installed tensorboardX-2.6.5
Collecting pysr
  Downloading pysr-1.5.10-py3-none-any.whl.metadata (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: click<9.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (8.4.2)
Collecting juliacall<0.9.27,>=0.9.24 (from pysr)
  Downloading juliacall-0.9.26-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: numpy<3.0.0,>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (2.0.2)
Requirement already satisfied: pandas<4.0.0,>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (2.2.2)
Requirement already satisfied: scikit-learn<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (1.6.1)
Requirement already satisfied: sympy<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (1.14.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (4.15.0)
Collecting juliapkg<0.2,>=0.1.17 (from juliacall<0.9.27,>=0.9.24->pysr)
  Downloading juliapkg-0.1.24-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0.0,>=0.21.0->pysr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0.0,>=0.21.0->pysr) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0.0,>=0.21.0->pysr) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy<2.0.0,>=1.0.0->pysr) (1.3.0)
Requirement already satisfied: filelock<4.0,>=3.16 in /usr/local/lib/python3.12/dist-packages (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr) (3.29.4)
Collecting semver<4.0,>=3.0 (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting tomli<3.0,>=2.0 (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr)
  Downloading tomli-2.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Requirement already satisfied: tomlkit<0.16,>=0.13.3 in /usr/local/lib/python3.12/dist-packages (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr) (0.14.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4.0.0,>=0.21.0->pysr) (1.17.0)
Downloading pysr-1.5.10-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.3/99.3 kB 7.7 MB/s eta 0:00:00
Downloading juliacall-0.9.26-py3-none-any.whl (12 kB)
Downloading juliapkg-0.1.24-py3-none-any.whl (22 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading tomli-2.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (253 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.3/253.3 kB 11.3 MB/s eta 0:00:00
Installing collected packages: tomli, semver, juliapkg, juliacall, pysr
Successfully installed juliacall-0.9.26 juliapkg-0.1.24 pysr-1.5.10 semver-3.0.4 tomli-2.4.1

In [ ]:
!git clone https://github.com/AndreasMadsen/stable-nalu.git

Cloning into 'stable-nalu'...
remote: Enumerating objects: 3003, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 3003 (delta 57), reused 109 (delta 55), pack-reused 2892 (from 1)
Receiving objects: 100% (3003/3003), 14.82 MiB | 19.99 MiB/s, done.
Resolving deltas: 100% (2271/2271), done.

In [ ]:
cd stable-nalu

/content/stable-nalu

In [ ]:
!python setup.py develop

/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running develop
/usr/local/lib/python3.12/dist-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
creating stable_nalu.egg-info
writing stable_nalu.egg-info/PKG-INFO
writing dependency_links to stable_nalu.egg-info/dependency_links.txt
writing requirements to stable_nalu.egg-info/requires.txt
writing top-level names to stable_nalu.egg-info/top_level.txt
writing manifest file 'stable_nalu.egg-info/SOURCES.txt'
reading manifest file 'stable_nalu.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'stable_nalu.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.12/dist-packages/stable-nalu.egg-link (link to .)
Adding stable-nalu 0.1.0 to easy-install.pth file

Installed /content/stable-nalu
Processing dependencies for stable-nalu==0.1.0
Searching for tensorboardx==2.6.5
Best match: tensorboardx 2.6.5
Adding tensorboardx 2.6.5 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for tensorboard==2.20.0
Best match: tensorboard 2.20.0
Adding tensorboard 2.20.0 to easy-install.pth file
Installing tensorboard script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for torchvision==0.26.0+cpu
Best match: torchvision 0.26.0+cpu
Adding torchvision 0.26.0+cpu to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for tensorflow==2.20.0
Best match: tensorflow 2.20.0
Adding tensorflow 2.20.0 to easy-install.pth file
Installing import_pb_to_tensorboard script to /usr/local/bin
Installing saved_model_cli script to /usr/local/bin
Installing tensorboard script to /usr/local/bin
Installing tf_upgrade_v2 script to /usr/local/bin
Installing tflite_convert script to /usr/local/bin
Installing toco script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for pandas==2.2.2
Best match: pandas 2.2.2
Adding pandas 2.2.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for scipy==1.16.3
Best match: scipy 1.16.3
Adding scipy 1.16.3 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for torch==2.11.0+cpu
Best match: torch 2.11.0+cpu
Adding torch 2.11.0+cpu to easy-install.pth file
Installing torchfrtrace script to /usr/local/bin
Installing torchrun script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for tqdm==4.67.3
Best match: tqdm 4.67.3
Adding tqdm 4.67.3 to easy-install.pth file
Installing tqdm script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for numpy==2.0.2
Best match: numpy 2.0.2
Adding numpy 2.0.2 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing numpy-config script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for protobuf==5.29.6
Best match: protobuf 5.29.6
Adding protobuf 5.29.6 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for packaging==26.2
Best match: packaging 26.2
Adding packaging 26.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for werkzeug==3.1.8
Best match: werkzeug 3.1.8
Adding werkzeug 3.1.8 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for tensorboard-data-server==0.7.2
Best match: tensorboard-data-server 0.7.2
Adding tensorboard-data-server 0.7.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for setuptools==75.2.0
Best match: setuptools 75.2.0
Adding setuptools 75.2.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for pillow==11.3.0
Best match: pillow 11.3.0
Adding pillow 11.3.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for markdown==3.10.2
Best match: markdown 3.10.2
Adding markdown 3.10.2 to easy-install.pth file
Installing markdown_py script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for grpcio==1.81.1
Best match: grpcio 1.81.1
Adding grpcio 1.81.1 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for absl-py==1.4.0
Best match: absl-py 1.4.0
Adding absl-py 1.4.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for ml-dtypes==0.5.4
Best match: ml-dtypes 0.5.4
Adding ml-dtypes 0.5.4 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for h5py==3.16.0
Best match: h5py 3.16.0
Adding h5py 3.16.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for keras==3.13.2
Best match: keras 3.13.2
Adding keras 3.13.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for wrapt==2.2.2
Best match: wrapt 2.2.2
Adding wrapt 2.2.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for typing-extensions==4.15.0
Best match: typing-extensions 4.15.0
Adding typing-extensions 4.15.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for termcolor==3.3.0
Best match: termcolor 3.3.0
Adding termcolor 3.3.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for six==1.17.0
Best match: six 1.17.0
Adding six 1.17.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for requests==2.32.4
Best match: requests 2.32.4
Adding requests 2.32.4 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for opt-einsum==3.4.0
Best match: opt-einsum 3.4.0
Adding opt-einsum 3.4.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for libclang==18.1.1
Best match: libclang 18.1.1
Adding libclang 18.1.1 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for google-pasta==0.2.0
Best match: google-pasta 0.2.0
Adding google-pasta 0.2.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for gast==0.7.0
Best match: gast 0.7.0
Adding gast 0.7.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for flatbuffers==25.12.19
Best match: flatbuffers 25.12.19
Adding flatbuffers 25.12.19 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for astunparse==1.6.3
Best match: astunparse 1.6.3
Adding astunparse 1.6.3 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for tzdata==2026.2
Best match: tzdata 2026.2
Adding tzdata 2026.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for pytz==2025.2
Best match: pytz 2025.2
Adding pytz 2025.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for python-dateutil==2.9.0.post0
Best match: python-dateutil 2.9.0.post0
Adding python-dateutil 2.9.0.post0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for fsspec==2025.3.0
Best match: fsspec 2025.3.0
Adding fsspec 2025.3.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for jinja2==3.1.6
Best match: jinja2 3.1.6
Adding jinja2 3.1.6 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for networkx==3.6.1
Best match: networkx 3.6.1
Adding networkx 3.6.1 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for sympy==1.14.0
Best match: sympy 1.14.0
Adding sympy 1.14.0 to easy-install.pth file
Installing isympy script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for filelock==3.29.4
Best match: filelock 3.29.4
Adding filelock 3.29.4 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for markupsafe==3.0.3
Best match: markupsafe 3.0.3
Adding markupsafe 3.0.3 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for optree==0.19.1
Best match: optree 0.19.1
Adding optree 0.19.1 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for namex==0.1.0
Best match: namex 0.1.0
Adding namex 0.1.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for rich==13.9.4
Best match: rich 13.9.4
Adding rich 13.9.4 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for certifi==2026.6.17
Best match: certifi 2026.6.17
Adding certifi 2026.6.17 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for urllib3==2.5.0
Best match: urllib3 2.5.0
Adding urllib3 2.5.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for idna==3.18
Best match: idna 3.18
Adding idna 3.18 to easy-install.pth file
Installing idna script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for charset-normalizer==3.4.7
Best match: charset-normalizer 3.4.7
Adding charset-normalizer 3.4.7 to easy-install.pth file
Installing normalizer script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for wheel==0.47.0
Best match: wheel 0.47.0
Adding wheel 0.47.0 to easy-install.pth file
Installing wheel script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for mpmath==1.3.0
Best match: mpmath 1.3.0
Adding mpmath 1.3.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for pygments==2.20.0
Best match: pygments 2.20.0
Adding pygments 2.20.0 to easy-install.pth file
Installing pygmentize script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for markdown-it-py==4.2.0
Best match: markdown-it-py 4.2.0
Adding markdown-it-py 4.2.0 to easy-install.pth file
Installing markdown-it script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for mdurl==0.1.2
Best match: mdurl 0.1.2
Adding mdurl 0.1.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Finished processing dependencies for stable-nalu==0.1.0

In [ ]:
import numpy as np
import pandas as pd
import pickle

In [ ]:
import torch
import torch.nn as nn
from stable_nalu.layer.re_regualized_linear_nac import ReRegualizedLinearNACLayer
from stable_nalu.layer.re_regualized_linear_nalu import ReRegualizedLinearNALULayer

/content/stable-nalu/stable_nalu/functional/gumbel.py:26: SyntaxWarning: invalid escape sequence '\i'
  tau: the temperature used, must be tau \in (0, \infty]. tau < 1
/content/stable-nalu/stable_nalu/layer/nac.py:13: SyntaxWarning: invalid escape sequence '\h'
  Asumming \hat{w} and \hat{m} are sampled from a uniform

In [ ]:
SEED=8
rnd=np.random.default_rng(0)
torch.manual_seed(SEED)

In [ ]:
!ls ../

models	sample_data  stable-nalu  test.xlsx

In [ ]:
data= pd.read_excel(r"../newBenchmarks_dataset.xlsx","rydberg")

In [ ]:
data.shape

(50, 14)

load the data for training. the data is collected by running the original paper.

In [ ]:
unique_train_indexes = list(rnd.choice(data.shape[0], 40, replace=False,))
unique_train_indexes

[np.int64(40),
 np.int64(23),
 np.int64(28),
 np.int64(45),
 np.int64(38),
 np.int64(46),
 np.int64(17),
 np.int64(43),
 np.int64(39),
 np.int64(3),
 np.int64(0),
 np.int64(13),
 np.int64(44),
 np.int64(41),
 np.int64(6),
 np.int64(24),
 np.int64(1),
 np.int64(37),
 np.int64(42),
 np.int64(21),
 np.int64(14),
 np.int64(30),
 np.int64(25),
 np.int64(16),
 np.int64(34),
 np.int64(8),
 np.int64(36),
 np.int64(11),
 np.int64(20),
 np.int64(22),
 np.int64(29),
 np.int64(18),
 np.int64(31),
 np.int64(15),
 np.int64(33),
 np.int64(47),
 np.int64(4),
 np.int64(9),
 np.int64(7),
 np.int64(26)]

In [ ]:
unique_test_indexes = [_ for _ in range(data.shape[0]) if _ not in unique_train_indexes]
len(unique_train_indexes),len(unique_test_indexes)

(40, 10)

In [ ]:
rydberg_train_X = data.loc[unique_train_indexes,['n1','n2']].values
rydberg_train_y = data.loc[unique_train_indexes,['y']].values

rydberg_test_X = torch.from_numpy(data.loc[unique_test_indexes,['n1','n2']].values)
rydberg_test_y = torch.from_numpy(data.loc[unique_test_indexes,['y']].values)

In [ ]:
rydberg_train_X.shape,rydberg_train_y.shape,rydberg_test_X.shape,rydberg_test_y.shape

((40, 2), (40, 1), torch.Size([10, 2]), torch.Size([10, 1]))

In [ ]:
from torch.utils.data import Dataset, DataLoader
loader = DataLoader(list(zip(rydberg_train_X,rydberg_train_y)), shuffle=True, batch_size=5)

In [ ]:
kwargs_nalu={'eps': 1e-07,'nac_oob': 'clip','regualizer_shape': 'linear','regualizer_z': 0,'mnac_epsilon': 0,'nalu_bias': False,'nalu_two_nac': True,'nalu_two_gate': False,'nalu_mul': 'mnac','nalu_gate': 'normal'}
kwargs_nac={'eps': 1e-07,'nac_oob': 'clip','regualizer_shape': 'linear','regualizer_z': 0,'mnac_epsilon': 0,'nalu_bias': False,'nalu_two_nac': False,'nalu_two_gate': False,'nalu_mul': 'normal','nalu_gate': 'normal'}

In [ ]:
class MyModel(nn.Module):
    def __init__(self, in_feats,h_feats, out_feat):
        super(MyModel, self).__init__()
        self.net0=nn.Linear(in_feats , h_feats*2,bias=False)
        self.net1=nn.Linear(h_feats*2 , h_feats,bias=False)
        self.leaKyrelu=torch.nn.LeakyReLU(0.1)
        self.net_nac=ReRegualizedLinearNACLayer(in_features=h_feats,out_features=h_feats,**kwargs_nac)
        self.net_nalu=ReRegualizedLinearNALULayer(in_features=h_feats,out_features=out_feat,**kwargs_nalu)
    def forward(self,inputs_):
        h=self.net0(inputs_.float())
        h=self.leaKyrelu(h)
        h=self.net1(h)
        h=self.leaKyrelu(h)
        h=self.net_nac(h)
        h=self.net_nalu(h)
        return h.double()
    def reset_parameters(self):
        torch.nn.init.xavier_uniform(self.net0.weight)
        torch.nn.init.xavier_uniform(self.net1.weight)
        self.net_nalu.reset_parameters()
        self.net_nac.reset_parameters()
    def regualizer(self):
        self.net_nalu.regualizer()
        self.net_nac.regualizer()

In [ ]:
net=MyModel(2,4,1)
net.reset_parameters()

/tmp/ipykernel_9338/2466979556.py:18: FutureWarning: `nn.init.xavier_uniform` is now deprecated in favor of `nn.init.xavier_uniform_`.
  torch.nn.init.xavier_uniform(self.net0.weight)
/tmp/ipykernel_9338/2466979556.py:19: FutureWarning: `nn.init.xavier_uniform` is now deprecated in favor of `nn.init.xavier_uniform_`.
  torch.nn.init.xavier_uniform(self.net1.weight)

In [ ]:
optim = torch.optim.RMSprop(net.parameters(), lr=0.001, weight_decay=1e-5)

In [ ]:
best_loss=np.inf
criterion = torch.nn.MSELoss()
for i in range(120000):
    loss_list=[]
    # net.train()
    for X_t,y_t in loader:
        optim.zero_grad()
        out=net(X_t)
        loss_train_criterion = criterion(y_t,out)
#         loss_train_regualizer =10 * r_w_scale * regualizers['W'] + regualizers['g'] + 0 * regualizers['z'] + 1 * regualizers['W-OOB']
        loss = loss_train_criterion #+ loss_train_regualizer
        loss.retain_grad()
        loss_list.append(loss.item())
        #################
        mea = torch.mean(torch.abs(y_t - out))
        loss.backward()
        optim.step()
    if i%1==0:
        with torch.no_grad():
            test_loss=criterion(rydberg_test_y,net(rydberg_test_X)).item()
            if test_loss<best_loss:
                best_loss=test_loss
                torch.save(net,f'../models/modelrydberg_2inputs_{i}.pt')

                print(f'saved at {i} with error {np.array(loss_list).mean()}, {best_loss}')

saved at 0 with error 187.8870893686519, 191.0186580638381
saved at 1 with error 181.81978199471726, 182.94734185069348
saved at 2 with error 168.46457047306038, 170.99838341792747
saved at 3 with error 152.9895325837299, 158.69610029157644
saved at 4 with error 138.01040768729808, 146.79415867920778
saved at 5 with error 123.80413960357407, 135.29225876123533
saved at 6 with error 110.22897353907503, 124.25500530483137
saved at 7 with error 97.30827310050427, 113.77162547663806
saved at 8 with error 85.13586116356294, 103.97395004479351
saved at 9 with error 73.84446224667168, 94.99322717621737
saved at 10 with error 63.5630181525481, 86.93018421514681
saved at 11 with error 54.40172543102166, 79.84947784374671
saved at 12 with error 46.42237726523108, 73.78577463883536
saved at 13 with error 39.61249000113932, 68.69493763172599
saved at 14 with error 33.97632952042923, 64.55967902509977
saved at 15 with error 29.436845013434112, 61.32844764140756
saved at 16 with error 25.930123509523185, 58.88303720010244
saved at 17 with error 23.313215567030035, 57.102515435132034
saved at 18 with error 21.396083901806723, 55.802748249075236
saved at 19 with error 20.00297435340239, 54.907329115145785
saved at 20 with error 19.070454588343168, 54.29037381262293
saved at 21 with error 18.36519516688935, 53.77802718242873
saved at 22 with error 17.89180816455289, 53.468776854611974
saved at 23 with error 17.641229966467378, 53.27506800755579
saved at 24 with error 17.545337981911967, 53.158315134386484
saved at 25 with error 17.437813618841368, 53.04627299408494
saved at 26 with error 17.329457529573254, 52.956895883922925
saved at 27 with error 17.291101682996672, 52.875732990523794
saved at 28 with error 17.33664299808505, 52.79460362309665
saved at 29 with error 17.162871066846545, 52.71696148161517
saved at 30 with error 17.15216529284691, 52.63298281833353
saved at 31 with error 17.118888248952555, 52.553176719321414
saved at 32 with error 16.97414504460539, 52.473014607466666
saved at 33 with error 16.93557497980013, 52.39349062264603
saved at 34 with error 16.841460847105374, 52.303992082409515
saved at 35 with error 16.878925814261045, 52.221622247121935
saved at 36 with error 16.76865187632631, 52.13223783915621
saved at 37 with error 16.71730662867908, 52.046648453753434
saved at 38 with error 16.735633552639477, 51.96399224747504
saved at 39 with error 16.65059174207707, 51.861183330994194
saved at 40 with error 16.571796521912354, 51.76424730858071
saved at 41 with error 16.510338459982886, 51.67438081723027
saved at 42 with error 16.443015402534098, 51.57878058268659
saved at 43 with error 16.421126817939246, 51.484011129996034
saved at 44 with error 16.352230564774786, 51.38878064833286
saved at 45 with error 16.317270257836878, 51.28645592570028
saved at 46 with error 16.272750571397925, 51.183346248863685
saved at 47 with error 16.30498818891657, 51.09080842571824
saved at 48 with error 16.121674404763695, 50.98914069033862
saved at 49 with error 16.114530820725353, 50.911895324789825
saved at 50 with error 16.14775911193291, 50.84115877079098
saved at 51 with error 15.933629055411783, 50.73134982966671
saved at 52 with error 15.89565246641666, 50.66297590552823
saved at 53 with error 15.846475691668772, 50.553229151304905
saved at 54 with error 15.825215398300033, 50.447638833683165
saved at 55 with error 15.711251773701322, 50.33455650461398
saved at 56 with error 15.776584952208216, 50.22891623220589
saved at 57 with error 15.744250746112769, 50.16016836240175
saved at 58 with error 15.741173710629027, 50.058347095949145
saved at 59 with error 15.568792861457117, 49.97098253824629
saved at 60 with error 15.541852332590684, 49.867347824845055
saved at 61 with error 15.410493756527302, 49.772684727309596
saved at 62 with error 15.377357181543559, 49.696409903444355
saved at 63 with error 15.275734904285835, 49.6111298141216
saved at 64 with error 15.224500839721765, 49.49905620438263
saved at 65 with error 15.319993800488984, 49.41977013944914
saved at 66 with error 15.155264244157625, 49.322441527927346
saved at 67 with error 15.172047313717096, 49.18270651314543
saved at 68 with error 15.064984356338863, 49.14436496413437
saved at 69 with error 15.03559973691462, 49.014692631367055
saved at 70 with error 14.95201845105481, 48.8936248941575
saved at 71 with error 14.979270204473272, 48.82859474770965
saved at 72 with error 14.924581847284948, 48.691652628480675
saved at 73 with error 14.85403993429538, 48.593696465429616
saved at 74 with error 14.742258423432974, 48.516831768712336
saved at 75 with error 14.77548906962356, 48.450799769756
saved at 76 with error 14.647838278139675, 48.32599696833512
saved at 77 with error 14.670122708899047, 48.187424089936435
saved at 79 with error 14.588484513007213, 48.02950190415693
saved at 80 with error 14.466688560651313, 47.96830074945932
saved at 81 with error 14.434747888844214, 47.865211321404544
saved at 82 with error 14.513607808426977, 47.72410963260224
saved at 83 with error 14.448440716951769, 47.64180374107441
saved at 85 with error 14.311760252336422, 47.574925102237614
saved at 86 with error 14.268539287841204, 47.552928235725986
saved at 87 with error 14.232046567630203, 47.4135170771479
saved at 88 with error 14.219500791511466, 47.303214949089956
saved at 89 with error 14.289497534482884, 47.20756397003799
saved at 92 with error 14.246477417982529, 47.001860789324304
saved at 93 with error 14.071323379184516, 46.95345745041696
saved at 94 with error 14.009988209068437, 46.90334741348671
saved at 95 with error 13.983311873491065, 46.82437135589375
saved at 97 with error 13.95940964937955, 46.571289175479286
saved at 98 with error 13.954315912819343, 46.54569849394507
saved at 101 with error 13.77884562692372, 46.38626796326248
saved at 102 with error 13.878099004685724, 46.381660704523725
saved at 103 with error 13.883187595372995, 46.31394559798956
saved at 105 with error 13.724299857177652, 46.25387225722289
saved at 106 with error 13.783115726181357, 46.1642888980147
saved at 107 with error 13.686764715558713, 46.049052535973
saved at 109 with error 13.737167348575309, 46.00405987916475
saved at 113 with error 13.648016148955836, 45.98782149732963
saved at 114 with error 13.592066279286076, 45.83490086032812
saved at 115 with error 13.640895317670177, 45.69461837800409
saved at 118 with error 13.594863708735915, 45.64916683264664
saved at 121 with error 13.608965050546104, 45.60422776773889
saved at 122 with error 13.47284634724419, 45.493976828670796
saved at 123 with error 13.467978609484849, 45.32224089478204
saved at 125 with error 13.484669156549687, 45.18659536256256
saved at 131 with error 13.5530152189083, 45.17554685702836
saved at 134 with error 13.576911441933596, 45.141430261701096
saved at 135 with error 13.529499070082629, 45.05959960436352
saved at 143 with error 13.433106014160916, 45.037155220694174
saved at 144 with error 13.455642557292965, 44.98709356163996
saved at 147 with error 13.436357219393974, 44.908944736292675
saved at 154 with error 13.394296923712565, 44.73169209372038
saved at 160 with error 13.317203205105326, 44.68658906707552
saved at 162 with error 13.49137193062505, 44.680364981900276
saved at 166 with error 13.324472280795721, 44.59679536969622
saved at 170 with error 13.377668913895437, 44.59307102199185
saved at 171 with error 13.355932911657021, 44.495896650778754
saved at 175 with error 13.416145088561551, 44.46870491929438
saved at 178 with error 13.402701368572878, 44.22334067848889
saved at 184 with error 13.280821778302519, 44.1158888508568
saved at 190 with error 13.221808924700728, 44.0246724932163
saved at 191 with error 13.226083574595737, 43.921587996630514
saved at 194 with error 13.222948090331828, 43.7194756440197
saved at 195 with error 13.173831144825357, 43.6185987851237
saved at 198 with error 13.113608959710838, 43.56471216476718
saved at 199 with error 13.127592294855353, 43.39019158501902
saved at 200 with error 13.028259134394215, 43.36253822739311
saved at 201 with error 13.104821418599347, 42.97106077378395
saved at 202 with error 12.982927587257748, 42.9203483967098
saved at 203 with error 12.90491909639319, 42.69444788837102
saved at 204 with error 12.986982425051453, 42.48114185064463
saved at 205 with error 12.805490624526296, 42.14216120073503
saved at 206 with error 12.729592731893892, 41.96978586951575
saved at 207 with error 12.612764389273833, 41.56000942289908
saved at 208 with error 12.668743354095398, 41.37772662585063
saved at 209 with error 12.566549238314442, 40.746842486304764
saved at 211 with error 12.20917245927488, 39.80648265044194
saved at 212 with error 12.07560602340868, 38.93780950044076
saved at 213 with error 11.7758971521822, 38.40730377849838
saved at 214 with error 11.602711363041387, 37.67080323905496
saved at 215 with error 11.428034466823625, 36.87704589835224
saved at 216 with error 11.07906927288997, 36.11715230466088
saved at 217 with error 10.706685681916083, 35.21839937627031
saved at 218 with error 10.344684825093895, 33.94188694490966
saved at 219 with error 10.022796884908384, 32.8103007935517
saved at 220 with error 9.581527290419968, 32.2591924814061
saved at 221 with error 9.244215048239294, 31.122005751069004
saved at 222 with error 8.98935032453956, 30.603686075940743
saved at 223 with error 8.691598254747827, 29.86075461743608
saved at 224 with error 8.477704962710606, 29.192630373619767
saved at 225 with error 8.271603201093976, 28.807946576703863
saved at 226 with error 8.12317026037374, 28.32625299284109
saved at 227 with error 7.91334148795708, 27.81363659604324
saved at 228 with error 7.777450799098661, 27.544689162959862
saved at 229 with error 7.645415668480667, 27.012959939157277
saved at 230 with error 7.477887877477759, 26.242622973515534
saved at 231 with error 7.344960834883128, 25.773254609780327
saved at 232 with error 7.19715338953572, 25.5555708681293
saved at 233 with error 7.035088712775833, 24.812014756586915
saved at 234 with error 6.946481981041371, 23.98894004201417
saved at 237 with error 6.438361358129875, 22.902968560553013
saved at 238 with error 6.34567823260309, 22.317805565189154
saved at 239 with error 6.114370994796215, 21.922319401414168
saved at 240 with error 6.0669908239146055, 21.624880809108454
saved at 241 with error 5.87467048442281, 20.65994568527724
saved at 242 with error 5.7695559210213, 20.300703047390453
saved at 243 with error 5.618641183098305, 19.63769282057886
saved at 244 with error 5.435495827800293, 19.462925106545224
saved at 245 with error 5.381436045021973, 18.42764426252381
saved at 246 with error 5.138394179897002, 18.05030231411996
saved at 247 with error 4.951420730305012, 17.688596118951825
saved at 248 with error 4.79430951737276, 17.060937999879382
saved at 249 with error 4.623244984089879, 16.076284805223665
saved at 250 with error 4.47808737733581, 15.820236145229472
saved at 251 with error 4.30241809430423, 15.213896266593604
saved at 252 with error 4.174910867747384, 14.846201289095706
saved at 253 with error 4.032865883215465, 13.524950284062612
saved at 254 with error 3.8728962844599955, 13.209776261201199
saved at 255 with error 3.692460068327876, 12.643036984664567
saved at 256 with error 3.579358266893631, 12.155960170004846
saved at 257 with error 3.3551628390992194, 11.919630827178953
saved at 258 with error 3.262794704695078, 10.769685921035716
saved at 259 with error 3.054106460719315, 10.54962504541054
saved at 260 with error 2.9291778507490744, 9.985002585830824
saved at 261 with error 2.807270338536118, 9.68505696988466
saved at 262 with error 2.607016682862387, 8.820616526233517
saved at 263 with error 2.4702775440918794, 8.452260557526566
saved at 264 with error 2.32325570979786, 8.055034494195377
saved at 265 with error 2.148915080220006, 7.023865197233009
saved at 267 with error 1.9078315078816606, 6.1714946579332
saved at 268 with error 1.8018381941857045, 6.059906650806182
saved at 269 with error 1.7291289725332248, 5.746686746157225
saved at 270 with error 1.5487315890457607, 4.813056443709008
saved at 271 with error 1.4842397929667028, 4.721686854245348
saved at 272 with error 1.4017486295013621, 4.1496819284987865
saved at 273 with error 1.3123208015958758, 3.9407744033217726
saved at 274 with error 1.199458020189958, 3.4867192123923423
saved at 275 with error 1.1441465080918647, 3.358602554413454
saved at 276 with error 1.0620762011142952, 3.1641340875193222
saved at 277 with error 1.006056414200698, 2.9220041119538296
saved at 278 with error 0.9122212746581497, 2.5990448229517953
saved at 279 with error 0.8820752109956218, 2.3665318717584554
saved at 280 with error 0.8245277464538209, 2.3249617639640925
saved at 281 with error 0.7627300649348101, 2.0622648130215873
saved at 282 with error 0.6981913215086977, 2.0006824127302267
saved at 283 with error 0.7517558849261092, 1.7694065744063987
saved at 284 with error 0.648161758775443, 1.6695600791953222
saved at 285 with error 0.6320413173984925, 1.6488703656669421
saved at 286 with error 0.66202921640337, 1.4796005606551303
saved at 287 with error 0.6080165367645534, 1.402112191365207
saved at 288 with error 0.609352898420331, 1.3149978612307585
saved at 289 with error 0.5920919461462295, 1.2348130689915204
saved at 292 with error 0.5632466815977065, 1.121278059083622
saved at 297 with error 0.5544574416683, 1.052056997526499
saved at 299 with error 0.5304306136596536, 0.9863333441526981
saved at 301 with error 0.5206193313146646, 0.9171130738356531
saved at 305 with error 0.49716142091577076, 0.8767891064428133
saved at 309 with error 0.5372832981588409, 0.8058722444189437
saved at 310 with error 0.5253212460865162, 0.7929015780817219
saved at 320 with error 0.5058254319945061, 0.7841666766438833
saved at 327 with error 0.44473308306759185, 0.7729299418944062
saved at 330 with error 0.517422681744262, 0.7581035434116807
saved at 12494 with error 0.21192584651716007, 0.722632116439898
saved at 12553 with error 0.24930846342413213, 0.7069434053374233
saved at 13263 with error 0.21314828650498926, 0.7045653230506259
saved at 16930 with error 0.1407266075008451, 0.688418876624767
saved at 17733 with error 0.08100336360299476, 0.6707999302724004
saved at 17816 with error 0.08380671755928695, 0.6497228878693442
saved at 18314 with error 0.06767091050084084, 0.6490424500892011
saved at 18384 with error 0.07818624782446444, 0.5372406382180217
saved at 23198 with error 0.08198217894497731, 0.5120020426202121
saved at 56349 with error 0.03991952830550331, 0.5097778398530596
saved at 57868 with error 0.03500041472573012, 0.4902097271566605
saved at 60862 with error 0.032480101996142485, 0.4584052421286328
saved at 64156 with error 0.023361923959325168, 0.45621665781151866
saved at 64238 with error 0.03808411864034926, 0.4350904098543421
saved at 66001 with error 0.025392324671825974, 0.4347961681557801
saved at 66240 with error 0.034036463472968626, 0.4283558684259085
saved at 66396 with error 0.027641528224310544, 0.4244229257582604
saved at 66632 with error 0.027671396092615992, 0.4202487354664566
saved at 66645 with error 0.02649740564589345, 0.41818435882301175
saved at 67016 with error 0.02822504866098069, 0.40941390264614447
saved at 67121 with error 0.02672105756917341, 0.39929703139108613
saved at 67374 with error 0.027629688942359162, 0.39338728497209186
saved at 67937 with error 0.030958467952290125, 0.3690603829780837
saved at 68397 with error 0.025949412200630243, 0.3674925455725161
saved at 68938 with error 0.024086774708888262, 0.34835522462474455
saved at 69037 with error 0.021795686300415985, 0.34141715269238815
saved at 69808 with error 0.0261035525505532, 0.327918604822897
saved at 69897 with error 0.026624218785524012, 0.32012697815343427
saved at 70843 with error 0.02378769795798516, 0.31342110835898745
saved at 71016 with error 0.019669847779427534, 0.3078729813516502
saved at 71032 with error 0.01952064305781216, 0.30615371935065105
saved at 71136 with error 0.021962205906390773, 0.2894282430706777
saved at 71250 with error 0.028455039346140562, 0.27732768492981374
saved at 71921 with error 0.023562846797433704, 0.27361015966008645
saved at 71973 with error 0.027089076443253, 0.26780877919663026
saved at 71977 with error 0.02410395231387167, 0.2655552277038515
saved at 72175 with error 0.026455955837390903, 0.2531403683849775
saved at 72392 with error 0.023397225401990886, 0.2518606398455162
saved at 72499 with error 0.01681052240547303, 0.23680654262897124
saved at 72570 with error 0.019859185787226126, 0.22882200907249653
saved at 72764 with error 0.027293721170029307, 0.20841359604117068
saved at 73283 with error 0.01599906754097747, 0.20705721583261577
saved at 73298 with error 0.033807600613550745, 0.1997030900467132
saved at 73568 with error 0.02861190688589719, 0.19433726594226702
saved at 73599 with error 0.018365247625717618, 0.18687737155440157
saved at 73674 with error 0.018094575530066624, 0.17374130654985007
saved at 73882 with error 0.01558540223278039, 0.16521749734801489
saved at 74062 with error 0.01412432803955575, 0.15462022870037082
saved at 74184 with error 0.01921194273503707, 0.15242447812324647
saved at 74300 with error 0.012064311434626421, 0.14878595139404954
saved at 74332 with error 0.01832440255772745, 0.144477019139281
saved at 74404 with error 0.011579271278455202, 0.14286204256095988
saved at 74445 with error 0.013554874460831555, 0.13988280143641918
saved at 74530 with error 0.01535969274058166, 0.1374385742894678
saved at 74562 with error 0.013050278025281664, 0.13269755781454548
saved at 74739 with error 0.014506974004442678, 0.13105805614365548
saved at 74798 with error 0.015851224925390008, 0.11740885989124587
saved at 74903 with error 0.02050977695946056, 0.11379297823558625
saved at 75003 with error 0.013743674110376627, 0.10841605255347535
saved at 75110 with error 0.01512467404467956, 0.10132807744085323
saved at 75277 with error 0.019520169791088837, 0.10061294278729851
saved at 75413 with error 0.008772361224546294, 0.09888019235096468
saved at 75429 with error 0.014831959666075221, 0.09562865919428454
saved at 75479 with error 0.018376540257722104, 0.09211994154396477
saved at 75645 with error 0.012645081409484529, 0.09092998283939051
saved at 75699 with error 0.009596873154995246, 0.08743319775567027
saved at 75749 with error 0.010139969622796258, 0.08604778690721704
saved at 75865 with error 0.007961912323573857, 0.07793151347105823
saved at 75883 with error 0.013950483926206382, 0.07649866800771517
saved at 75917 with error 0.011172083912442593, 0.07570636683547058
saved at 76064 with error 0.014152220922240432, 0.06905304448374994
saved at 76285 with error 0.013023599823176142, 0.06590470207988221
saved at 76485 with error 0.018307402527907836, 0.06386029139181512
saved at 76729 with error 0.007608184696619015, 0.059565939423919315
saved at 76733 with error 0.00678365154972054, 0.05954968453633548
saved at 76773 with error 0.008509995784500735, 0.05187848479770389
saved at 77022 with error 0.014977117193235018, 0.047637259404403026
saved at 77055 with error 0.01241462483956517, 0.04078554516178774
saved at 77920 with error 0.010416009664028544, 0.04029714252222197
saved at 78130 with error 0.009439043577653263, 0.03872706556476038
saved at 78536 with error 0.007599815927538129, 0.038006024012764365
saved at 78983 with error 0.007598617797754127, 0.03455205637107108
saved at 79372 with error 0.005989105871171801, 0.03445052204344722
saved at 79924 with error 0.007324603489165125, 0.031752781668512885
saved at 80566 with error 0.011628947546113965, 0.031546209270484564
saved at 80806 with error 0.008965531263006681, 0.03021992698145094
saved at 80927 with error 0.0062759688828115286, 0.02927469035031584
saved at 81102 with error 0.005168896868168219, 0.029049037048952852
saved at 81216 with error 0.00460255852816654, 0.027284542617742897
saved at 81420 with error 0.006222362964566868, 0.025982105063669818

In [ ]:
i

119999

load best model saved for measuring the performance on all datasets

In [ ]:
net1=torch.load('../models/modelrydberg_2inputs_119704.pt',weights_only=False)#99842

In [ ]:
res_=[]
for n1,n2 in ((1,5),(2,4),(1,8),(2,8),(3,8),(4,8),(5,8),(6,8),(7,8),(1,9),(2,9),(3,9),(4,9),(5,9),(6,9),(7,9),(8,9),(1,10),(2,10),(3,10),(4,10),(5,10),(6,10),(7,10),(8,10),(9,10)):
    m=net1(torch.from_numpy(np.array([[n1,n2]])))
    obs=np.log(1/(1.10E+07*((1/n1**2)-(1/n2**2))))
    res_.append([n1,n2,m.detach().numpy()[0][0],obs])

In [ ]:
res_ = pd.DataFrame(res_)
res_

    0   1          2          3
0   1   5 -16.136345 -16.172584
1   2   4 -14.621179 -14.539429
2   1   8 -16.164640 -16.197657
3   2   8 -14.780425 -14.762573
4   3   8 -13.398439 -13.864631
5   4   8 -13.094972 -13.153135
6   5   8 -12.694060 -12.499209
7   6   8 -11.879654 -11.803208
8   7   8 -10.984447 -10.870753
9   1   9 -16.153603 -16.200983
10  2   9 -14.840574 -14.776468
11  3   9 -13.570587 -13.898398
12  4   9 -13.202707 -13.220755
13  5   9 -12.989275 -12.625433
14  6   9 -12.588282 -12.042100
15  7   9 -11.630079 -11.392872
16  8   9 -10.714685 -10.493287
17  1  10 -16.131363 -16.203355
18  2  10 -14.897568 -14.786289
19  3  10 -13.607748 -13.921871
20  4  10 -13.280404 -13.266464
21  5  10 -13.204008 -12.706848
22  6  10 -13.265645 -12.183600
23  7  10 -12.601875 -11.648241
24  8  10 -11.586450 -11.032871
25  9  10 -10.527440 -10.158225

In [ ]:
(res_[3] - res_[2]).abs().mean()

np.float64(0.2642748706907793)

In [ ]:
n1=10
n2=11
m=net1(torch.from_numpy(np.array([[n1,n2]])))
obs=np.log(1/(1.10E+07*((1/n1**2)-(1/n2**2))))
print(m.detach().numpy()[0][0],obs)

-10.417257308959961 -9.856967536901236

In [ ]:
pd.DataFrame(np.concatenate([data.loc[:,['n1','n2']].values,net1(torch.from_numpy(data.loc[:,['n1','n2']].values)).detach().numpy()],axis=1))

      0    1          2
0   4.0  5.0 -12.340358
1   4.0  7.0 -12.944950
2   6.0  7.0 -11.342027
3   4.0  6.0 -12.735641
4   6.0  7.0 -11.342027
5   2.0  3.0 -14.326780
6   2.0  5.0 -14.570326
7   2.0  7.0 -14.717483
8   1.0  6.0 -16.155441
9   3.0  5.0 -13.426346
10  2.0  7.0 -14.717483
11  4.0  5.0 -12.340358
12  1.0  2.0 -15.858246
13  3.0  6.0 -13.598581
14  4.0  5.0 -12.340358
15  5.0  6.0 -11.792444
16  1.0  2.0 -15.858246
17  4.0  6.0 -12.735641
18  6.0  7.0 -11.342027
19  2.0  3.0 -14.326780
20  1.0  2.0 -15.858246
21  1.0  3.0 -16.071920
22  1.0  7.0 -16.165062
23  4.0  6.0 -12.735641
24  3.0  4.0 -13.145185
25  5.0  7.0 -12.226146
26  3.0  5.0 -13.426346
27  6.0  7.0 -11.342027
28  4.0  7.0 -12.944950
29  4.0  6.0 -12.735641
30  2.0  7.0 -14.717483
31  4.0  5.0 -12.340358
32  6.0  7.0 -11.342027
33  1.0  7.0 -16.165062
34  2.0  6.0 -14.652112
35  5.0  6.0 -11.792444
36  4.0  6.0 -12.735641
37  3.0  7.0 -13.659786
38  1.0  6.0 -16.155441
39  6.0  7.0 -11.342027
40  6.0  7.0 -11.342027
41  4.0  7.0 -12.944950
42  3.0  6.0 -13.598581
43  5.0  6.0 -11.792444
44  3.0  7.0 -13.659786
45  4.0  7.0 -12.944950
46  1.0  4.0 -16.108322
47  4.0  6.0 -12.735641
48  1.0  4.0 -16.108322
49  1.0  2.0 -15.858246