Running on Colab, will download and install neccesary packages.
upload the "newBenchmarks_dataset.xlsx" in the main folder

In [1]:
!pip install tensorboardX
!pip install pysr

Collecting tensorboardX
  Downloading tensorboardx-2.6.5-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from tensorboardX) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorboardX) (26.2)
Requirement already satisfied: protobuf>=3.20 in /usr/local/lib/python3.12/dist-packages (from tensorboardX) (5.29.6)
Downloading tensorboardx-2.6.5-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 3.0 MB/s eta 0:00:00
Installing collected packages: tensorboardX
Successfully installed tensorboardX-2.6.5
Collecting pysr
  Downloading pysr-1.5.10-py3-none-any.whl.metadata (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: click<9.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (8.4.1)
Collecting juliacall<0.9.27,>=0.9.24 (from pysr)
  Downloading juliacall-0.9.26-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: numpy<3.0.0,>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (2.0.2)
Requirement already satisfied: pandas<4.0.0,>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (2.2.2)
Requirement already satisfied: scikit-learn<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (1.6.1)
Requirement already satisfied: sympy<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (1.14.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (4.15.0)
Collecting juliapkg<0.2,>=0.1.17 (from juliacall<0.9.27,>=0.9.24->pysr)
  Downloading juliapkg-0.1.24-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0.0,>=0.21.0->pysr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0.0,>=0.21.0->pysr) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0.0,>=0.21.0->pysr) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy<2.0.0,>=1.0.0->pysr) (1.3.0)
Requirement already satisfied: filelock<4.0,>=3.16 in /usr/local/lib/python3.12/dist-packages (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr) (3.29.3)
Collecting semver<4.0,>=3.0 (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting tomli<3.0,>=2.0 (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr)
  Downloading tomli-2.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Requirement already satisfied: tomlkit<0.16,>=0.13.3 in /usr/local/lib/python3.12/dist-packages (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr) (0.13.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4.0.0,>=0.21.0->pysr) (1.17.0)
Downloading pysr-1.5.10-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.3/99.3 kB 10.4 MB/s eta 0:00:00
Downloading juliacall-0.9.26-py3-none-any.whl (12 kB)
Downloading juliapkg-0.1.24-py3-none-any.whl (22 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading tomli-2.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (253 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.3/253.3 kB 17.7 MB/s eta 0:00:00
Installing collected packages: tomli, semver, juliapkg, juliacall, pysr
Successfully installed juliacall-0.9.26 juliapkg-0.1.24 pysr-1.5.10 semver-3.0.4 tomli-2.4.1

In [2]:
!git clone https://github.com/AndreasMadsen/stable-nalu.git

Cloning into 'stable-nalu'...
remote: Enumerating objects: 3003, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 3003 (delta 57), reused 109 (delta 55), pack-reused 2892 (from 1)
Receiving objects: 100% (3003/3003), 14.82 MiB | 14.26 MiB/s, done.
Resolving deltas: 100% (2271/2271), done.

In [3]:
cd stable-nalu

/content/stable-nalu

In [4]:
!python setup.py develop

/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running develop
/usr/local/lib/python3.12/dist-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/usr/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
creating stable_nalu.egg-info
writing stable_nalu.egg-info/PKG-INFO
writing dependency_links to stable_nalu.egg-info/dependency_links.txt
writing requirements to stable_nalu.egg-info/requires.txt
writing top-level names to stable_nalu.egg-info/top_level.txt
writing manifest file 'stable_nalu.egg-info/SOURCES.txt'
reading manifest file 'stable_nalu.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'stable_nalu.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.12/dist-packages/stable-nalu.egg-link (link to .)
Adding stable-nalu 0.1.0 to easy-install.pth file

Installed /content/stable-nalu
Processing dependencies for stable-nalu==0.1.0
Searching for tensorboardx==2.6.5
Best match: tensorboardx 2.6.5
Adding tensorboardx 2.6.5 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for tensorboard==2.20.0
Best match: tensorboard 2.20.0
Adding tensorboard 2.20.0 to easy-install.pth file
Installing tensorboard script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for torchvision==0.26.0+cpu
Best match: torchvision 0.26.0+cpu
Adding torchvision 0.26.0+cpu to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for tensorflow==2.20.0
Best match: tensorflow 2.20.0
Adding tensorflow 2.20.0 to easy-install.pth file
Installing import_pb_to_tensorboard script to /usr/local/bin
Installing saved_model_cli script to /usr/local/bin
Installing tensorboard script to /usr/local/bin
Installing tf_upgrade_v2 script to /usr/local/bin
Installing tflite_convert script to /usr/local/bin
Installing toco script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for pandas==2.2.2
Best match: pandas 2.2.2
Adding pandas 2.2.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for scipy==1.16.3
Best match: scipy 1.16.3
Adding scipy 1.16.3 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for torch==2.11.0+cpu
Best match: torch 2.11.0+cpu
Adding torch 2.11.0+cpu to easy-install.pth file
Installing torchfrtrace script to /usr/local/bin
Installing torchrun script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for tqdm==4.67.3
Best match: tqdm 4.67.3
Adding tqdm 4.67.3 to easy-install.pth file
Installing tqdm script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for numpy==2.0.2
Best match: numpy 2.0.2
Adding numpy 2.0.2 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing numpy-config script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for protobuf==5.29.6
Best match: protobuf 5.29.6
Adding protobuf 5.29.6 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for packaging==26.2
Best match: packaging 26.2
Adding packaging 26.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for werkzeug==3.1.8
Best match: werkzeug 3.1.8
Adding werkzeug 3.1.8 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for tensorboard-data-server==0.7.2
Best match: tensorboard-data-server 0.7.2
Adding tensorboard-data-server 0.7.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for setuptools==75.2.0
Best match: setuptools 75.2.0
Adding setuptools 75.2.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for pillow==11.3.0
Best match: pillow 11.3.0
Adding pillow 11.3.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for markdown==3.10.2
Best match: markdown 3.10.2
Adding markdown 3.10.2 to easy-install.pth file
Installing markdown_py script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for grpcio==1.81.1
Best match: grpcio 1.81.1
Adding grpcio 1.81.1 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for absl-py==1.4.0
Best match: absl-py 1.4.0
Adding absl-py 1.4.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for ml-dtypes==0.5.4
Best match: ml-dtypes 0.5.4
Adding ml-dtypes 0.5.4 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for h5py==3.16.0
Best match: h5py 3.16.0
Adding h5py 3.16.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for keras==3.13.2
Best match: keras 3.13.2
Adding keras 3.13.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for wrapt==2.2.1
Best match: wrapt 2.2.1
Adding wrapt 2.2.1 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for typing-extensions==4.15.0
Best match: typing-extensions 4.15.0
Adding typing-extensions 4.15.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for termcolor==3.3.0
Best match: termcolor 3.3.0
Adding termcolor 3.3.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for six==1.17.0
Best match: six 1.17.0
Adding six 1.17.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for requests==2.32.4
Best match: requests 2.32.4
Adding requests 2.32.4 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for opt-einsum==3.4.0
Best match: opt-einsum 3.4.0
Adding opt-einsum 3.4.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for libclang==18.1.1
Best match: libclang 18.1.1
Adding libclang 18.1.1 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for google-pasta==0.2.0
Best match: google-pasta 0.2.0
Adding google-pasta 0.2.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for gast==0.7.0
Best match: gast 0.7.0
Adding gast 0.7.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for flatbuffers==25.12.19
Best match: flatbuffers 25.12.19
Adding flatbuffers 25.12.19 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for astunparse==1.6.3
Best match: astunparse 1.6.3
Adding astunparse 1.6.3 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for tzdata==2026.2
Best match: tzdata 2026.2
Adding tzdata 2026.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for pytz==2025.2
Best match: pytz 2025.2
Adding pytz 2025.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for python-dateutil==2.9.0.post0
Best match: python-dateutil 2.9.0.post0
Adding python-dateutil 2.9.0.post0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for fsspec==2025.3.0
Best match: fsspec 2025.3.0
Adding fsspec 2025.3.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for jinja2==3.1.6
Best match: jinja2 3.1.6
Adding jinja2 3.1.6 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for networkx==3.6.1
Best match: networkx 3.6.1
Adding networkx 3.6.1 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for sympy==1.14.0
Best match: sympy 1.14.0
Adding sympy 1.14.0 to easy-install.pth file
Installing isympy script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for filelock==3.29.3
Best match: filelock 3.29.3
Adding filelock 3.29.3 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for markupsafe==3.0.3
Best match: markupsafe 3.0.3
Adding markupsafe 3.0.3 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for optree==0.19.1
Best match: optree 0.19.1
Adding optree 0.19.1 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for namex==0.1.0
Best match: namex 0.1.0
Adding namex 0.1.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for rich==13.9.4
Best match: rich 13.9.4
Adding rich 13.9.4 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for certifi==2026.5.20
Best match: certifi 2026.5.20
Adding certifi 2026.5.20 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for urllib3==2.5.0
Best match: urllib3 2.5.0
Adding urllib3 2.5.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for idna==3.18
Best match: idna 3.18
Adding idna 3.18 to easy-install.pth file
Installing idna script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for charset-normalizer==3.4.7
Best match: charset-normalizer 3.4.7
Adding charset-normalizer 3.4.7 to easy-install.pth file
Installing normalizer script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for wheel==0.47.0
Best match: wheel 0.47.0
Adding wheel 0.47.0 to easy-install.pth file
Installing wheel script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for mpmath==1.3.0
Best match: mpmath 1.3.0
Adding mpmath 1.3.0 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Searching for pygments==2.20.0
Best match: pygments 2.20.0
Adding pygments 2.20.0 to easy-install.pth file
Installing pygmentize script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for markdown-it-py==4.2.0
Best match: markdown-it-py 4.2.0
Adding markdown-it-py 4.2.0 to easy-install.pth file
Installing markdown-it script to /usr/local/bin

Using /usr/local/lib/python3.12/dist-packages
Searching for mdurl==0.1.2
Best match: mdurl 0.1.2
Adding mdurl 0.1.2 to easy-install.pth file

Using /usr/local/lib/python3.12/dist-packages
Finished processing dependencies for stable-nalu==0.1.0

In [5]:
import numpy as np
import pandas as pd
import pickle
from datetime import datetime

In [6]:
# import pysr
!pwd ..

/content/stable-nalu

In [7]:
import torch
import torch.nn as nn
from stable_nalu.layer.re_regualized_linear_nac import ReRegualizedLinearNACLayer
from stable_nalu.layer.re_regualized_linear_nalu import ReRegualizedLinearNALULayer

/content/stable-nalu/stable_nalu/functional/gumbel.py:26: SyntaxWarning: invalid escape sequence '\i'
  tau: the temperature used, must be tau \in (0, \infty]. tau < 1
/content/stable-nalu/stable_nalu/layer/nac.py:13: SyntaxWarning: invalid escape sequence '\h'
  Asumming \hat{w} and \hat{m} are sampled from a uniform

In [8]:
SEED=5
rnd=np.random.default_rng(SEED)
torch.manual_seed(SEED)

In [9]:
!ls ../..

bin	 datalab  home	  lib32   media  proc		    root  srv  tools
boot	 dev	  kaggle  lib64   mnt	 python-apt	    run   sys  usr
content  etc	  lib	  libx32  opt	 python-apt.tar.xz  sbin  tmp  var

In [ ]:
pd.ExcelFile(r"../../content/newBenchmarks_dataset.xlsx",).sheet_names

['Sheet1', 'ideal_gas', 'bode', 'Sheet4', 'schechter']

In [ ]:
data= pd.read_excel(r"../../content/newBenchmarks_dataset.xlsx","schechter")
data.shape

(27, 10)

rescale the L and output

In [15]:
data['y'] *= 1e10
data['L'] /= 1e7

In [16]:
data.describe()

,Unnamed: 0,L,y,Unnamed: 3,Unnamed: 4,Unnamed: 5,y (without noise),Unnamed: 7,Unnamed: 8,Unnamed: 9
count,27.000000,27.000000,2.700000e+01,0.0,0.0,27.000000,2.700000e+01,0.0,2.700000e+01,2.700000e+01
mean,13.000000,31.683371,8.598217e+00,NaN,NaN,13.000000,8.389833e-10,NaN,8.389833e-10,4.735491e-24
std,7.937254,62.665479,1.552668e+01,NaN,NaN,7.937254,1.481676e-09,NaN,1.481676e-09,1.296270e-23
min,0.000000,0.106283,3.907915e-08,NaN,NaN,0.000000,4.221978e-18,NaN,4.221978e-18,0.000000e+00
25%,6.500000,0.393318,1.325802e-02,NaN,NaN,6.500000,1.394803e-12,NaN,1.394803e-12,1.716561e-27
50%,13.000000,5.639191,4.520406e-01,NaN,NaN,13.000000,3.812370e-11,NaN,3.812370e-11,4.846761e-26
75%,19.500000,34.239765,1.014247e+01,NaN,NaN,19.500000,1.149393e-09,NaN,1.149393e-09,1.809458e-24
max,26.000000,288.039552,6.028528e+01,NaN,NaN,26.000000,5.584883e-09,NaN,5.584883e-09,5.045802e-23

In [ ]:
unique_train_indexes = list(rnd.choice(data.shape[0], int(data.shape[0]*0.7), replace=False,))

In [18]:
unique_test_indexes = [_ for _ in range(data.shape[0]) if _ not in unique_train_indexes]
len(unique_train_indexes),len(unique_test_indexes)

(18, 9)

In [47]:
data

,Unnamed: 0,L,y,Unnamed: 3,Unnamed: 4,Unnamed: 5,y (without noise),Unnamed: 7,Unnamed: 8,Unnamed: 9
0,0,34.548092,1.251978e-02,NaN,NaN,0,1.362534e-12,NaN,1.362534e-12,1.413639e-26
1,1,5.639191,4.520406e-01,NaN,NaN,1,3.812370e-11,NaN,3.812370e-11,1.227846e-25
2,2,0.110788,6.028528e+01,NaN,NaN,2,5.312551e-09,NaN,5.312551e-09,4.714929e-23
3,3,9.251380,1.744117e-01,NaN,NaN,3,1.821618e-11,NaN,1.821618e-11,4.846761e-26
4,4,0.719453,4.587813e+00,NaN,NaN,4,5.491831e-10,NaN,5.491831e-10,9.305782e-25
5,5,0.403327,1.042629e+01,NaN,NaN,5,1.113841e-09,NaN,1.113841e-09,5.169879e-24
6,6,1.663702,2.548899e+00,NaN,NaN,6,1.933863e-10,NaN,1.933863e-10,0.000000e+00
7,7,288.039552,3.907915e-08,NaN,NaN,7,4.221978e-18,NaN,4.221978e-18,1.525337e-31
8,8,7.385681,2.380065e-01,NaN,NaN,8,2.571858e-11,NaN,2.571858e-11,9.693523e-27
9,9,19.343681,2.580331e-02,NaN,NaN,9,5.020383e-12,NaN,5.020383e-12,2.665719e-26
10,10,0.106283,5.318045e+01,NaN,NaN,10,5.584883e-09,NaN,5.584883e-09,5.045802e-23
11,11,143.940154,2.233932e-05,NaN,NaN,11,3.092453e-15,NaN,3.092453e-15,5.798128e-29
12,12,110.900958,1.331912e-04,NaN,NaN,12,1.585436e-14,NaN,1.585436e-14,5.774462e-28
13,13,1.790743,2.102827e+00,NaN,NaN,13,1.761447e-10,NaN,1.761447e-10,1.033976e-25
14,14,74.690234,1.063412e-03,NaN,NaN,14,1.084424e-13,NaN,1.084424e-13,1.262177e-29
15,15,0.371570,9.858643e+00,NaN,NaN,15,1.230593e-09,NaN,1.230593e-09,2.688337e-24
16,16,0.624819,5.074866e+00,NaN,NaN,16,6.529181e-10,NaN,6.529181e-10,8.271806e-25
17,17,34.960735,1.329157e-02,NaN,NaN,17,1.321269e-12,NaN,1.321269e-12,1.615587e-27
18,18,0.297587,1.723274e+01,NaN,NaN,18,1.611061e-09,NaN,1.611061e-09,6.203855e-25
19,19,0.383310,1.290104e+01,NaN,NaN,19,1.184946e-09,NaN,1.184946e-09,3.101927e-24
20,20,0.211083,2.649434e+01,NaN,NaN,20,2.441223e-09,NaN,2.441223e-09,1.199412e-23
21,21,7.595799,2.639742e-01,NaN,NaN,21,2.465910e-11,NaN,2.465910e-11,2.908057e-26
22,22,24.112702,4.044778e-02,NaN,NaN,22,3.184509e-12,NaN,3.184509e-12,1.009742e-26
23,23,0.424643,9.329915e+00,NaN,NaN,23,1.046193e-09,NaN,1.046193e-09,3.929108e-24
24,24,0.327185,1.688935e+01,NaN,NaN,24,1.436091e-09,NaN,1.436091e-09,6.203855e-25
25,25,53.676920,4.470255e-03,NaN,NaN,25,3.736021e-13,NaN,3.736021e-13,6.563323e-28
26,26,33.931437,1.322447e-02,NaN,NaN,26,1.427072e-12,NaN,1.427072e-12,1.817536e-27

In [ ]:
schechter_train_X = data.loc[unique_train_indexes,['L']].values
schechter_train_y = data.loc[unique_train_indexes,['y']].values

schechter_test_X = torch.from_numpy(data.loc[unique_test_indexes,['L']].values)
schechter_test_y = torch.from_numpy(data.loc[unique_test_indexes,['y']].values)

In [ ]:
schechter_train_X.shape,schechter_train_y.shape,schechter_test_X.shape,schechter_test_y.shape

((18, 1), (18, 1), torch.Size([9, 1]), torch.Size([9, 1]))

In [ ]:
from torch.utils.data import Dataset, DataLoader
loader = DataLoader(list(zip(schechter_train_X,schechter_train_y)), shuffle=True, batch_size=6)

In [22]:
kwargs_nalu={'eps': 1e-07,'nac_oob': 'clip','regualizer_shape': 'linear','regualizer_z': 0,'mnac_epsilon': 0,'nalu_bias': False,'nalu_two_nac': True,'nalu_two_gate': False,'nalu_mul': 'normal','nalu_gate': 'normal'}
kwargs_nac={'eps': 1e-07,'nac_oob': 'clip','regualizer_shape': 'linear','regualizer_z': 0,'mnac_epsilon': 0,'nalu_bias': False,'nalu_two_nac': False,'nalu_two_gate': False,'nalu_mul': 'normal','nalu_gate': 'normal'}

In [ ]:
class MyModel(nn.Module):
    def __init__(self, in_feats,h_feats, out_feat):
        super(MyModel, self).__init__()
        self.net0=nn.Linear(in_feats , h_feats*2,bias=False)
        self.net1=nn.Linear(h_feats*2 , h_feats,bias=False)
        # self.net1_1=nn.Linear(h_feats*2 , h_feats*2,bias=False)
        self.leaKyrelu=torch.nn.LeakyReLU(0.1)
        self.net_nac=ReRegualizedLinearNACLayer(in_features=h_feats,out_features=h_feats,**kwargs_nac)
        self.net_nalu=ReRegualizedLinearNALULayer(in_features=h_feats,out_features=out_feat,**kwargs_nalu)
    def forward(self,inputs_):
        h=self.net0(inputs_.float())
        h=self.leaKyrelu(h)
        # h=self.net1_1(h)
        # h=self.leaKyrelu(h)
        h=self.net1(h)
        h=self.leaKyrelu(h)
        h=self.net_nac(h)
        h=self.net_nalu(h)
        return h.double()
    def reset_parameters(self):
        torch.nn.init.xavier_uniform(self.net0.weight)
        torch.nn.init.xavier_uniform(self.net1.weight)
        # torch.nn.init.xavier_uniform(self.net1_1.weight)
        self.net_nalu.reset_parameters()
        self.net_nac.reset_parameters()
    def regualizer(self):
        self.net_nalu.regualizer()
        self.net_nac.regualizer()

In [24]:
net=MyModel(1,2,1)
net.reset_parameters()

/tmp/ipykernel_1908/3821075369.py:21: FutureWarning: `nn.init.xavier_uniform` is now deprecated in favor of `nn.init.xavier_uniform_`.
  torch.nn.init.xavier_uniform(self.net0.weight)
/tmp/ipykernel_1908/3821075369.py:22: FutureWarning: `nn.init.xavier_uniform` is now deprecated in favor of `nn.init.xavier_uniform_`.
  torch.nn.init.xavier_uniform(self.net1.weight)

In [25]:
print(f"start {datetime.now()}")

start 2026-06-28 15:55:19.121453

In [26]:
optim = torch.optim.Adam(net.parameters(), lr=0.001, weight_decay=1e-5)#

In [ ]:
best_loss=np.inf
criterion = torch.nn.HuberLoss()
for i in range(10000):
    loss_list=[]
    # net.train()
    for X_t,y_t in loader:
        optim.zero_grad()
        out=net(X_t)
        loss_train_criterion = criterion(y_t,out)
#         loss_train_regualizer =10 * r_w_scale * regualizers['W'] + regualizers['g'] + 0 * regualizers['z'] + 1 * regualizers['W-OOB']
        loss = loss_train_criterion #+ loss_train_regualizer
        loss.retain_grad()
        loss_list.append(loss.item())
        #################
        mea = torch.mean(torch.abs(y_t - out))
        loss.backward()
        optim.step()
    if i%1==0:
        with torch.no_grad():
            test_loss=criterion(schechter_test_y,net(schechter_test_X)).item()
            if test_loss<best_loss:
                best_loss=test_loss
                torch.save(net,f'../../content/models/modelschechter_2inputs_{i}.pt')

                print(f'saved at {i} with error {np.array(loss_list).mean()}, {best_loss}')

saved at 0 with error 6.827979302354641, 11.396131258472845
saved at 1 with error 6.823878889441645, 11.390413764302577
saved at 2 with error 6.818091327567608, 11.385022900016805
saved at 3 with error 6.813384569403676, 11.379484344398763
saved at 4 with error 6.808499115738395, 11.37394534868541
saved at 5 with error 6.804247056280239, 11.368372206393955
saved at 6 with error 6.799729302532682, 11.362785265523327
saved at 7 with error 6.795070232831752, 11.357282277171771
saved at 8 with error 6.79015854940783, 11.351903299008143
saved at 9 with error 6.786189904318817, 11.346328618259552
saved at 10 with error 6.781538784616724, 11.340777489107833
saved at 11 with error 6.776416476729859, 11.335315982593926
saved at 12 with error 6.772584779415748, 11.329585979965167
saved at 13 with error 6.7674241191635645, 11.323961168504635
saved at 14 with error 6.763322153154715, 11.31813406857995
saved at 15 with error 6.758611151437347, 11.312254794837916
saved at 16 with error 6.75387206497387, 11.306254006169773
saved at 17 with error 6.749063111138033, 11.300085902425359
saved at 18 with error 6.743695100843358, 11.2940414187349
saved at 19 with error 6.738976929392407, 11.287511617341115
saved at 20 with error 6.734013156915187, 11.280729630889692
saved at 21 with error 6.728255411356149, 11.273801197961204
saved at 22 with error 6.723164669414235, 11.266300043514555
saved at 23 with error 6.7179072565350815, 11.258310026394154
saved at 24 with error 6.710945143144138, 11.250265701501002
saved at 25 with error 6.704638915304325, 11.24174804553425
saved at 26 with error 6.697993908767393, 11.23272616214641
saved at 27 with error 6.690789307282621, 11.223350565226042
saved at 28 with error 6.683278443884341, 11.21329114210814
saved at 29 with error 6.677126407130474, 11.202000463343975
saved at 30 with error 6.6678173690036, 11.190405007805019
saved at 31 with error 6.658588437076723, 11.178113763497445
saved at 32 with error 6.649212406930418, 11.164906260889785
saved at 33 with error 6.639716106653686, 11.150435278331544
saved at 34 with error 6.628923940810665, 11.1350316916723
saved at 35 with error 6.618753482567534, 11.118160696406505
saved at 36 with error 6.605989719709837, 11.100392822757147
saved at 37 with error 6.593770410777448, 11.08126186861051
saved at 38 with error 6.577132146138427, 11.061850849171941
saved at 39 with error 6.562168042778044, 11.04078956433034
saved at 40 with error 6.547598223596471, 11.017588635283245
saved at 41 with error 6.528902436274509, 10.993054639882184
saved at 42 with error 6.51151647360298, 10.966028769747934
saved at 43 with error 6.493855052941799, 10.93532833890515
saved at 44 with error 6.472425307413769, 10.90131821954167
saved at 45 with error 6.449545060124161, 10.863467231851207
saved at 46 with error 6.419690696153116, 10.822469096434794
saved at 47 with error 6.390934086896991, 10.775576717075873
saved at 48 with error 6.361342084570366, 10.72000256891528
saved at 49 with error 6.313685474260936, 10.660664053147594
saved at 50 with error 6.277046770135769, 10.585302039177554
saved at 51 with error 6.2175718956630694, 10.500010809059606
saved at 52 with error 6.185030671622424, 10.377436992606786
saved at 53 with error 6.09359052950177, 10.218586304510016
saved at 54 with error 5.983512908162846, 9.742407710302826
saved at 57 with error 5.800046951377528, 9.623857041698283
saved at 58 with error 5.685507154593721, 9.389905015038924
saved at 59 with error 5.546556312917365, 9.129421074821328
saved at 60 with error 5.442340882905718, 8.725648989168517
saved at 61 with error 5.314755038423649, 8.229408929483576
saved at 62 with error 5.149644393634836, 7.94069509504074
saved at 65 with error 5.00004339884322, 7.4623248924181205
saved at 66 with error 6.207328485112197, 6.880583443228541
saved at 72 with error 4.494866397322004, 6.754118117861248
saved at 73 with error 4.357772353855976, 6.609800950430601
saved at 74 with error 4.278717834998218, 6.479111090200717
saved at 75 with error 4.222643307123524, 6.373294231617414
saved at 76 with error 4.190001427846762, 6.292648104895079
saved at 77 with error 4.198515907311642, 6.204265788346942
saved at 78 with error 4.196395394875321, 6.129433629330823
saved at 79 with error 4.217649380949083, 6.061540371144769
saved at 80 with error 4.162009260656798, 6.051367433071675
saved at 83 with error 4.144748770934173, 6.029691409954035
saved at 84 with error 4.131587418099035, 6.024518476551123
saved at 85 with error 4.144116979306339, 5.997772706749471
saved at 103 with error 4.024022929220149, 5.966725479268283
saved at 104 with error 3.991643330281772, 5.962473076020334
saved at 105 with error 3.988075848467131, 5.955290100334319
saved at 106 with error 3.980624142767189, 5.9520504281221704
saved at 107 with error 3.978640741283465, 5.939822651970249
saved at 109 with error 3.9670072243574026, 5.929685712481834
saved at 110 with error 3.9646735343159247, 5.909355337028431
saved at 114 with error 3.934500947253735, 5.90776442105528
saved at 115 with error 3.92942584692596, 5.902951339075968
saved at 116 with error 3.930153629792239, 5.888317109123233
saved at 117 with error 3.9189522777255923, 5.872549419238898
saved at 118 with error 3.9127164061016675, 5.863027785589594
saved at 119 with error 3.9128617681937308, 5.840967980311184
saved at 120 with error 3.90412531087714, 5.825544683949245
saved at 121 with error 3.8986122597783535, 5.81055090995773
saved at 122 with error 3.88940142820667, 5.806527698439852
saved at 123 with error 3.885288504200427, 5.793857567051634
saved at 124 with error 3.876673712165466, 5.788161461529598
saved at 126 with error 3.8703469154758037, 5.771513102400641
saved at 127 with error 3.8603391196809205, 5.768768393114654
saved at 128 with error 3.8595116485416843, 5.756443330431654
saved at 129 with error 3.8495308028744795, 5.746738665346449
saved at 130 with error 3.8444753700849046, 5.733676868967598
saved at 132 with error 3.836854891041714, 5.730767938156129
saved at 133 with error 3.8274817397913594, 5.715569523995657
saved at 134 with error 3.821931589755738, 5.702047649143499
saved at 135 with error 3.818252643417163, 5.696879975783666
saved at 136 with error 3.818556972196415, 5.669406673469917
saved at 137 with error 3.8094960797845125, 5.667002749381955
saved at 138 with error 3.8031040953476567, 5.661458158927364
saved at 139 with error 3.7973896188682255, 5.637914328326273
saved at 140 with error 3.78954439769786, 5.621614819478347
saved at 141 with error 3.7846856223644862, 5.600821805720745
saved at 142 with error 3.7814176632827468, 5.578947183976731
saved at 143 with error 3.771224927788115, 5.571796070261254
saved at 144 with error 3.766035350472006, 5.556740758884307
saved at 145 with error 3.7601965842027787, 5.538654190647016
saved at 146 with error 3.7535889422226902, 5.520672472261441
saved at 147 with error 3.7450773542069666, 5.5056433393657285
saved at 148 with error 3.73964797640947, 5.4901421234094325
saved at 149 with error 3.7322556092385306, 5.478887798849267
saved at 150 with error 3.7249859949263358, 5.4665698099975595
saved at 151 with error 3.725803490277348, 5.445525280128648
saved at 152 with error 3.711421997796027, 5.435932286625973
saved at 153 with error 3.706317669187802, 5.424149376802343
saved at 154 with error 3.698774793825713, 5.412493237891871
saved at 155 with error 3.696771327884812, 5.399647719134293
saved at 156 with error 3.688280669578029, 5.392449181161838
saved at 157 with error 3.6795712329374015, 5.374895236020985
saved at 158 with error 3.6706027416039535, 5.364520023020919
saved at 159 with error 3.663568243870573, 5.349437248137395
saved at 160 with error 3.6619465781745983, 5.332184431320571
saved at 161 with error 3.6492621586262524, 5.318598985094823
saved at 162 with error 3.638003522195788, 5.310413744410701
saved at 163 with error 3.6396303616734724, 5.297391879262132
saved at 164 with error 3.6221216599224877, 5.289929237437281
saved at 165 with error 3.6139170289971503, 5.282210485516185
saved at 166 with error 3.6193920565582904, 5.2679498667290305
saved at 167 with error 3.623870218091924, 5.254911535585534
saved at 168 with error 3.5877899887833586, 5.2484245795944
saved at 169 with error 3.5871241716428823, 5.244425810813388
saved at 170 with error 3.5621413027928255, 5.242058528851379
saved at 173 with error 3.5382009162284795, 5.241204719279141
saved at 174 with error 3.53215179158545, 5.23985381134989
saved at 175 with error 3.526305193659098, 5.236757443630604
saved at 176 with error 3.522862785690336, 5.2320568405920405
saved at 177 with error 3.514991070038507, 5.229573960335994
saved at 178 with error 3.5104115038525348, 5.2284400263266875
saved at 180 with error 3.4983649628637328, 5.226745845381165
saved at 181 with error 3.4925162062986614, 5.216333108625708
saved at 182 with error 3.4876899428505284, 5.204887177384875
saved at 184 with error 3.4774383656116092, 5.193477012995773
saved at 185 with error 3.469591821131733, 5.188803395023214
saved at 186 with error 3.466331649375359, 5.178604097253099
saved at 187 with error 3.4607079094406377, 5.175442832873302
saved at 188 with error 3.4539340312580715, 5.172208328516213
saved at 189 with error 3.4550800595277096, 5.160595161673763
saved at 190 with error 3.4511893634328366, 5.150513251555974
saved at 191 with error 3.4396089402982426, 5.147535344948014
saved at 192 with error 3.4340279310251316, 5.14445636806067
saved at 195 with error 3.431764973963006, 5.132159217902333
saved at 200 with error 3.4003727992625468, 5.124251765960589
saved at 201 with error 3.3884206847071003, 5.122963377611956
saved at 202 with error 3.387922767355698, 5.111141346459536
saved at 203 with error 3.378158364091904, 5.107975429122231
saved at 204 with error 3.3759244951782876, 5.107957000014348
saved at 207 with error 3.366086453445561, 5.097027980071813
saved at 208 with error 3.360692685838836, 5.092392671689163
saved at 209 with error 3.350270575427249, 5.088999833327547
saved at 210 with error 3.345005188431189, 5.085276645911816
saved at 211 with error 3.346006162800735, 5.071561136314442
saved at 212 with error 3.3389259033767, 5.063569431847423
saved at 213 with error 3.3337786721941036, 5.062246057362527
saved at 214 with error 3.3405214840750617, 5.049839637481851
saved at 219 with error 3.307931526816622, 5.048736226647201
saved at 220 with error 3.2991897983094707, 5.0470179967768365
saved at 221 with error 3.298617708602611, 5.03998417356449
saved at 222 with error 3.291347365682792, 5.032941208669656
saved at 223 with error 3.288779253238712, 5.032656433201669
saved at 224 with error 3.2833368134543086, 5.024616192795639
saved at 227 with error 3.276985647113719, 5.012717465536433
saved at 231 with error 3.251297329890144, 5.005674974823385
saved at 232 with error 3.2475255663487563, 5.004094156975896
saved at 233 with error 3.2417685327603816, 4.9990921519193465
saved at 234 with error 3.238465672081494, 4.990370296866944
saved at 235 with error 3.2354520369166124, 4.987305785393441
saved at 239 with error 3.2400961858458963, 4.966050487169216
saved at 240 with error 3.215225671358047, 4.959869705615427
saved at 241 with error 3.2273646031572802, 4.946418062514059
saved at 251 with error 3.166776474603092, 4.943641008630135
saved at 252 with error 3.166715638761486, 4.93252869788701
saved at 254 with error 3.158014620063098, 4.924450017345617
saved at 255 with error 3.160320574417303, 4.9111471896691965
saved at 256 with error 3.150697673962867, 4.906126944410797
saved at 257 with error 3.1450995866826212, 4.902535249311693
saved at 258 with error 3.1388574948109924, 4.902110134247296
saved at 265 with error 3.112831065424006, 4.896188232038865
saved at 266 with error 3.1077097027342107, 4.885948321198176
saved at 270 with error 3.0964575929115843, 4.878475516332549
saved at 271 with error 3.086177196992613, 4.870177350341169
saved at 272 with error 3.0875920695888746, 4.868932352034078
saved at 273 with error 3.0783548372380296, 4.8612418433380205
saved at 276 with error 3.0697470918570304, 4.856122735243239
saved at 277 with error 3.0653393906722926, 4.853110121836769
saved at 278 with error 3.0647597861354936, 4.8380516786232395
saved at 280 with error 3.056422743598309, 4.830189662975655
saved at 281 with error 3.0546790226975524, 4.819756512935488
saved at 282 with error 3.047315052865416, 4.816984420229673
saved at 288 with error 3.02869488494202, 4.8159912096291615
saved at 293 with error 3.004829739105402, 4.809878711325138
saved at 294 with error 3.001344024196299, 4.799167377821741
saved at 298 with error 2.9944301157385844, 4.786865813323368
saved at 301 with error 2.9755863217151837, 4.785641573974523
saved at 302 with error 2.9745230234360114, 4.776764854553144
saved at 303 with error 2.9842555124951904, 4.757717756607706
saved at 304 with error 2.9664394379688432, 4.756596882306157
saved at 309 with error 2.946065253957308, 4.7531487897308455
saved at 314 with error 2.935726457305874, 4.750102775399993
saved at 315 with error 2.9241513533610317, 4.7463994856752745
saved at 316 with error 2.9253187928514883, 4.734290651031121
saved at 318 with error 2.916910995429171, 4.73292178904545
saved at 319 with error 2.9110715479769262, 4.728314428821851
saved at 320 with error 2.907378206331988, 4.7281323856513495
saved at 321 with error 2.90290208987217, 4.72274466205462
saved at 322 with error 2.9022029735571775, 4.717092682225127
saved at 323 with error 2.9006896572578533, 4.707734153167505
saved at 324 with error 2.9008708427217074, 4.6990383015237684
saved at 337 with error 2.852540169202245, 4.683976103551733
saved at 338 with error 2.8440100785336395, 4.673526508733835
saved at 339 with error 2.844631694086821, 4.669026451323422
saved at 340 with error 2.8374793228033792, 4.661686217313811
saved at 345 with error 2.8339539112577725, 4.646380832684273
saved at 347 with error 2.8148335375896987, 4.643095282667033
saved at 352 with error 2.7978742255772513, 4.638109812110162
saved at 354 with error 2.795169874060196, 4.629818903350506
saved at 356 with error 2.7829098858926407, 4.629155558790266
saved at 362 with error 2.7643095562014133, 4.622374956768817
saved at 363 with error 2.7660464015902213, 4.607070810218911
saved at 364 with error 2.7545483434482496, 4.602650231240997
saved at 365 with error 2.756754394162355, 4.591784914376448
saved at 371 with error 2.7329250219753383, 4.5916221305888065
saved at 372 with error 2.734593861640036, 4.5800374580312955
saved at 374 with error 2.721876643231963, 4.577913130047253
saved at 379 with error 2.7050991879443558, 4.573746419590305
saved at 380 with error 2.7039394087445685, 4.572096524503407
saved at 381 with error 2.70059047387049, 4.5703947735011825
saved at 382 with error 2.6958288900488157, 4.565991920335682
saved at 383 with error 2.695896201453559, 4.557467621385772
saved at 384 with error 2.6928904229576847, 4.54907787322141
saved at 385 with error 2.6891516643015305, 4.538308585219071
saved at 386 with error 2.685193636201021, 4.5345058133436345
saved at 387 with error 2.679388740511373, 4.530455088367292
saved at 388 with error 2.6774438532016887, 4.524963668143567
saved at 389 with error 2.682340890078906, 4.515821356651658
saved at 393 with error 2.6672750242163104, 4.51429116504851
saved at 398 with error 2.644443035080863, 4.512520618414327
saved at 405 with error 2.624421918072974, 4.507675842844599
saved at 406 with error 2.6256117925430473, 4.493157363141383
saved at 407 with error 2.6158036696040625, 4.486343214783021
saved at 408 with error 2.6122889262489575, 4.482244454734596
saved at 409 with error 2.607772528667163, 4.479245635038767
saved at 410 with error 2.6076390058156305, 4.472913388518416
saved at 411 with error 2.609314216804298, 4.464324538244137
saved at 414 with error 2.6068535941155466, 4.4618929316124145
saved at 419 with error 2.58712723909658, 4.453719378213797
saved at 420 with error 2.5746405401235957, 4.452169458615168
saved at 423 with error 2.5662408798949135, 4.450294601239325
saved at 425 with error 2.5614233474172665, 4.449805484835931
saved at 426 with error 2.5553648925199184, 4.441831948550083
saved at 427 with error 2.5522676934716024, 4.43453715957737
saved at 428 with error 2.5497640181893915, 4.429831455698872
saved at 429 with error 2.5574730270963406, 4.416494981910386
saved at 431 with error 2.5413522619785742, 4.413026351474635
saved at 432 with error 2.5432009525637964, 4.40926959812097
saved at 433 with error 2.5353784148559257, 4.404172444463271
saved at 438 with error 2.5254119679163787, 4.395876011361081
saved at 439 with error 2.516272005036502, 4.391645230742883
saved at 442 with error 2.5114539466726566, 4.38510980519485
saved at 447 with error 2.4925137542749227, 4.379154517510586
saved at 448 with error 2.486607418113124, 4.37739808711315
saved at 449 with error 2.4849853350011695, 4.372261258201295
saved at 450 with error 2.4940502421384596, 4.360516073041538
saved at 456 with error 2.4622674337427255, 4.356720277237317
saved at 458 with error 2.457032976562339, 4.355007813947692
saved at 460 with error 2.4689152073360554, 4.342906989067245
saved at 461 with error 2.4519652821315945, 4.333142161427806
saved at 462 with error 2.4561793437300996, 4.321908355388235
saved at 464 with error 2.4460254052024637, 4.3163933313561635
saved at 471 with error 2.42713410469078, 4.310484112285848
saved at 475 with error 2.4051206363262736, 4.306581314390162
saved at 476 with error 2.403577062884598, 4.303927636566381
saved at 477 with error 2.400377989391974, 4.298649920452275
saved at 478 with error 2.408158254216775, 4.2859069722360665
saved at 480 with error 2.401273808671215, 4.276186052265783
saved at 481 with error 2.3914751667516168, 4.269316837004562
saved at 488 with error 2.3671620419037285, 4.268970215119115
saved at 489 with error 2.36372246211106, 4.2626422999974425
saved at 492 with error 2.356943991050706, 4.261245116576908
saved at 493 with error 2.3516591831546902, 4.257618279177421
saved at 494 with error 2.3483744691070543, 4.253999789736278
saved at 495 with error 2.345399629979541, 4.249985916141302
saved at 496 with error 2.3480337918373864, 4.249613804528346
saved at 497 with error 2.346427113140742, 4.248553792999705
saved at 498 with error 2.337641271489288, 4.23941493982261
saved at 500 with error 2.33149634066973, 4.235347993152301
saved at 501 with error 2.3346538601812807, 4.2343682091677985
saved at 502 with error 2.3288236389327412, 4.223553275565009
saved at 503 with error 2.3219389206544245, 4.221013853680196
saved at 504 with error 2.32002403996669, 4.214072279300457
saved at 505 with error 2.3224816849112773, 4.211104357062771
saved at 506 with error 2.3203652724527046, 4.202738032667155
saved at 507 with error 2.314485631136366, 4.196546648847311
saved at 508 with error 2.3175872829570503, 4.189310124489921
saved at 509 with error 2.3130753718478534, 4.184274592288967
saved at 521 with error 2.2712631717318903, 4.181142321399378
saved at 522 with error 2.2775496232233703, 4.173038264840572
saved at 523 with error 2.2682792977547686, 4.168051440596572
saved at 525 with error 2.261835281291805, 4.165008634152936
saved at 527 with error 2.2523606151109057, 4.164765945788464
saved at 528 with error 2.2536538896696294, 4.1602362290630985
saved at 537 with error 2.226599774802503, 4.155465610709399
saved at 538 with error 2.221630016848527, 4.151617276065078
saved at 541 with error 2.213454630192266, 4.147337549713573
saved at 542 with error 2.214907037249279, 4.140712248912021
saved at 543 with error 2.204647410391292, 4.140394013550754
saved at 544 with error 2.203346169558983, 4.137354149513091
saved at 545 with error 2.201846158502171, 4.133334757735397
saved at 558 with error 2.1581642785601693, 4.128477527146799
saved at 559 with error 2.1548358714467137, 4.123057330988994
saved at 560 with error 2.1554019398942246, 4.115172123940089
saved at 563 with error 2.1453251855166844, 4.108298980813798

In [28]:
print(f"end {datetime.now()}")

end 2026-06-28 15:56:29.977335

In [29]:
for name, param in net.named_parameters():
    if 'weight' in name:
        print(f"Layer: {name} | Size: {param.size()} | Values : {param.data}")

Layer: net0.weight | Size: torch.Size([4, 1]) | Values : tensor([[-1.0449],
        [ 0.3815],
        [ 0.5988],
        [ 0.1341]])
Layer: net1.weight | Size: torch.Size([2, 4]) | Values : tensor([[ 1.0337,  0.2410, -0.9799,  0.7975],
        [ 1.0208, -1.1483, -1.6355, -0.0303]])

In [30]:
i

9999

In [31]:
loss

tensor(0.1172, dtype=torch.float64, grad_fn=<HuberLossBackward0>)

In [ ]:
net1=torch.load(f'../../content/models/modelschechter_2inputs_6954.pt',weights_only=False)#99842

extrapolation dataset

In [33]:
res_=[]
for L in np.linspace(0.5,30,100)/10:#rnd.uniform(300.,500.,10):
    obs = (0.002/250000000)*np.power((L/25),-1.2)*(np.exp(-1*L/25))*1e10
    model = net1(torch.from_numpy(np.array([[L]]))).detach().numpy()[0][0]
    res_.append([L,model,obs])

In [34]:
res_ = pd.DataFrame(res_,columns=['L','model','Obs'])
res_['diff'] = (res_['Obs'] - res_['model']).abs()

In [35]:
res_['diff'].mean()

np.float64(0.20810849665719225)

In [36]:
res_

           L       model         Obs      diff
0   0.050000  130.057251  138.351988  8.294737
1   0.079798   75.703499   78.857225  3.153726
2   0.109596   52.384567   53.822104  1.437536
3   0.139394   39.600285   40.281330  0.681046
4   0.169192   31.592525   31.887707  0.295182
..       ...         ...         ...       ...
95  2.880808    0.906041    0.953139  0.047097
96  2.910606    0.892247    0.940320  0.048072
97  2.940404    0.878763    0.927790  0.049027
98  2.970202    0.865579    0.915540  0.049960
99  3.000000    0.852686    0.903560  0.050875

[100 rows x 4 columns]

evaluation the best model on training/validation

In [ ]:
data= pd.read_excel(r"../../content/newBenchmarks_dataset.xlsx","schechter")
# data

In [40]:
data['y'] *= 1e10
data['L'] /= 1e7

In [41]:
pd.DataFrame([net1(torch.from_numpy(data['L'].values.reshape(-1,1))).detach().numpy().flatten(),data['y'].values]).T

            0             1
0    0.001618  1.251978e-02
1    0.294155  4.520406e-01
2   51.730289  6.028528e+01
3    0.097684  1.744117e-01
4    5.656230  4.587813e+00
5   11.360560  1.042629e+01
6    1.954265  2.548899e+00
7    0.011591  3.907915e-08
8    0.168110  2.380065e-01
9    0.008096  2.580331e-02
10  54.286232  5.318045e+01
11   0.005792  2.233932e-05
12   0.004463  1.331912e-04
13   1.771106  2.102827e+00
14   0.003006  1.063412e-03
15  12.524022  9.858643e+00
16   6.716094  5.074866e+00
17   0.001615  1.329157e-02
18  16.288086  1.723274e+01
19  12.069654  1.290104e+01
20  24.390570  2.649434e+01
21   0.157783  2.639742e-01
22   0.003346  4.044778e-02
23  10.684337  9.329915e+00
24  14.561864  1.688935e+01
25   0.002164  4.470255e-03
26   0.001626  1.322447e-02

In [42]:
criterion(net1(torch.from_numpy(data['L'].values.reshape(-1,1))),torch.from_numpy(data['y'].values.reshape(-1,1)))

tensor(0.6780, dtype=torch.float64, grad_fn=<HuberLossBackward0>)